import PRODUCT_FILTER_ACTION_TYPE from "reducers/product-filter/productFilterActionType"

type ProductFilterActionType = typeof PRODUCT_FILTER_ACTION_TYPE.BRAND_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.CLEAR_PRODUCTS_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.CATEGORY_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.ESRB_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.FAST_DELIVERY_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.SEARCH_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.SORT_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.OUT_OF_STOCK_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.RATINGS_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.PRICERANGE_FILTER
    | typeof PRODUCT_FILTER_ACTION_TYPE.PLATFORM_FILTER


export default ProductFilterActionType;