const PRODUCT_FILTER_ACTION_TYPE = {
    CLEAR_PRODUCTS_FILTER: "CLEAR_PRODUCTS_FILTER",
    CATEGORY_FILTER: "CATEGORY_FILTER",
    PRICERANGE_FILTER: "PRICERANGE_FILTER",
    BRAND_FILTER: "BRAND_FILTER",
    IN_STOCK_FILTER: "IN_STOCK_FILTER",
    FAST_DELIVERY_FILTER: "FAST_DELIVERY_FILTER",
    ESRB_FILTER: "ESRB_FILTER",
    SORT_FILTER: "SORT_FILTER",
    PLATFORM_FILTER: "PLATFORM_FILTER",
    RATINGS_FILTER: "RATINGS_FILTER",
    SEARCH_FILTER: "SEARCH_FILTER",
}

export default PRODUCT_FILTER_ACTION_TYPE;