const PRODUCT_ACTION_TYPE = {
    SET_PRODUCTS_FILTER: "SET_PRODUCTS_FILTER",
    UPDATE_PRODUCTS_LIST: "UPDATE_PRODUCTS_LIST",
    CLEAR_PRODUCTS_FILTER: "CLEAR_PRODUCTS_FILTER"
    // CATEGORY_FILTER: "CATEGORY_FILTER",
    // PRICE_FILTER: "PRICE_FILTER",
    // BRAND_FILTER: "BRAND_FILTER",
    // IN_STOCK_FILTER: "IN_STOCK_FILTER",
    // FAST_DELIVERY_FILTER: "FAST_DELIVERY_FILTER",
    // ESRB_FILTER: "ESRB_FILTER",
    // SORT_FILTER: "SORT_FILTER",
    // PLATFORM_FILTER: "PLATFORM_FILTER",
    // RATINGS_FILTER: "RATINGS_FILTER"
}

export default PRODUCT_ACTION_TYPE;